### ISSUE TITLE
Range of Action Space

### ISSUE THREAD

**Issue by AerysNan** [PCCproject/PCC-RL#13]
Hi, thanks for the clearly written testbed for RL congestion control.
After going through the codes, I notice that [here](https://github.com/PCCproject/PCC-RL/blob/master/src/gym/network_sim.py#L379) the range of action space is set to `[-1e12, 1e12]`. Even though later a `DELTA_SCALE` (default to 0.25) is applied to the action, it's still a fairly large action space. I wonder why we use this range here without any normalization, could you please kindly give some explanations? Thanks a lot.

**Comment by r02b** [comment]
Hi,

Please note (Sec 3.1 in the paper) that the next rate is given by:
![image](https://user-images.githubusercontent.com/7995410/113865978-6daf1e80-97b5-11eb-9e39-39fd772ce029.png)
where the alpha here is actually the delta scale you refer to (yes, bad notation), which is a scaling factor used to dampen oscillations.
So, the action is the ratio (times that factor) between the current rate and the next rate, which is why we used this action space. We found that modeling it this way, instead of, for example, having the action being the next rate, the model generalize better.

(FYI - the default scale is actually 0.025)
